#spring.datasource.url=jdbc:postgresql://localhost:5432/andqxai
server:
  port: 9090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tirgobot
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver
  profiles:
    active: #activeProfile#
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
#  config:
#    activate:
#      on-profile: spring.profiles.active@
springdoc:
  swagger-ui:
    path: /swagger-ui
    enabled: true
  api-docs:
    path: /api-docs
